### ISSUE TITLE
sharing the website on facebook doesnt show any image.. 

### ISSUE THREAD

**Issue by pcalessio** [ItalianiDigitaliLondra/website#3]
probably need to add meta data

**Comment by mtt87** [comment]
https://github.com/ItalianiDigitaliLondra/website/commit/2e7831d8f47593aefe793b40c85bdf0ecea098e1

I think Facebook cache the response for an hour or so, I will check in a few hours or tomorrow morning if the image is still not there when sharing the content @pcalessio

**Comment by pcalessio** [comment]
:+1:
